FROM pytorch/pytorch:2.7.1-cuda11.8-cudnn9-runtime

ENV DDP_ADDR=0.0.0.0
ENV DDP_PORT=50050

ENV GRPC_ADDR=10.0.1.12
ENV GRPC_PORT=50051

ENV WORLD_SIZE=1
ENV RANK=0

EXPOSE 50050 50050

WORKDIR /output/Sign-AI

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY scripts/ ./scripts/
COPY src/ ./src/
COPY pyproject.toml ./

WORKDIR /output/data
RUN touch test.1

WORKDIR /output/Sign-AI
ENTRYPOINT ["poe", "worker"]