# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04\x64\x61ta\"@\n\rStreamRequest\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\x12\n\nworld_size\x18\x02 \x01(\x05\x12\r\n\x05split\x18\x03 \x01(\t\"5\n\x06Tensor\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"\x9c\x01\n\x0eStreamResponse\x12\x1e\n\x08keypoint\x18\x01 \x01(\x0b\x32\x0c.data.Tensor\x12#\n\rkeypoint_mask\x18\x02 \x01(\x0b\x32\x0c.data.Tensor\x12\x1f\n\tembedding\x18\x03 \x01(\x0b\x32\x0c.data.Tensor\x12$\n\x0e\x65mbedding_mask\x18\x04 \x01(\x0b\x32\x0c.data.Tensor\";\n\x10SaveModelRequest\x12\x13\n\x0bmodel_bytes\x18\x01 \x01(\x0c\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"5\n\x11SaveModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"_\n\x0bHyperparams\x12\x15\n\rlearning_rate\x18\x01 \x01(\x01\x12\x15\n\rmodel_version\x18\x02 \x01(\x05\x12\x0e\n\x06\x65pochs\x18\x03 \x01(\x05\x12\x12\n\nbatch_size\x18\x04 \x01(\x05\"l\n\x0fModelParameters\x12\x13\n\x0boutput_size\x18\x01 \x01(\x05\x12\x13\n\x0bhidden_size\x18\x02 \x01(\x05\x12\r\n\x05nhead\x18\x03 \x01(\x05\x12\x0e\n\x06\x66\x66_dim\x18\x04 \x01(\x05\x12\x10\n\x08n_layers\x18\x05 \x01(\x05\x32\xf2\x01\n\x0b\x44\x61taService\x12\x39\n\nStreamData\x12\x13.data.StreamRequest\x1a\x14.data.StreamResponse0\x01\x12<\n\tSaveModel\x12\x16.data.SaveModelRequest\x1a\x17.data.SaveModelResponse\x12\x30\n\x0eGetHyperparams\x12\x0b.data.Empty\x1a\x11.data.Hyperparams\x12\x38\n\x12GetModelParameters\x12\x0b.data.Empty\x1a\x15.data.ModelParametersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STREAMREQUEST']._serialized_start=20
  _globals['_STREAMREQUEST']._serialized_end=84
  _globals['_TENSOR']._serialized_start=86
  _globals['_TENSOR']._serialized_end=139
  _globals['_STREAMRESPONSE']._serialized_start=142
  _globals['_STREAMRESPONSE']._serialized_end=298
  _globals['_SAVEMODELREQUEST']._serialized_start=300
  _globals['_SAVEMODELREQUEST']._serialized_end=359
  _globals['_SAVEMODELRESPONSE']._serialized_start=361
  _globals['_SAVEMODELRESPONSE']._serialized_end=414
  _globals['_EMPTY']._serialized_start=416
  _globals['_EMPTY']._serialized_end=423
  _globals['_HYPERPARAMS']._serialized_start=425
  _globals['_HYPERPARAMS']._serialized_end=520
  _globals['_MODELPARAMETERS']._serialized_start=522
  _globals['_MODELPARAMETERS']._serialized_end=630
  _globals['_DATASERVICE']._serialized_start=633
  _globals['_DATASERVICE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
